### ISSUE TITLE
Can there be some simple installation instructions? 

### ISSUE THREAD

**Issue by arnaudh** [jaketmp/matlab-quicklook#2]
I'm not familiar with C... could you provide the README with some bash commands to execute in order to install the quicklook plugin? 
That would help a lot!

Thanks

**Comment by jaketmp** [comment]
Install instructions are with the built download - see the [releases page](https://github.com/jaketmp/matlab-quicklook/releases) for details, just copy `matlab.qlgenerator` where directed.

**Comment by JeffFessler** [comment]
Newer macOS versions have more security about downloaded files, understandably.
Users will likely get an error message about permissions.

The install instructions probably need to mention a step like this:
`xattr -c ~/Library/QuickLook/matlab.qlgenerator`
which clears the "extended attributes" from the file.  That worked for me.

A more surgical approach (that I have not tested, but was recommended by the bots) is
`xattr -r -d com.apple.quarantine ~/Library/QuickLook/matlab.qlgenerator`
